### ISSUE TITLE
Add option to rename the filter headline

### ISSUE THREAD

**Issue by Lednerb** [Mahi-Mahi/SpatieTagsNovaFilter#1]
Hello and thanks for this nice nova package!

It would be a good addition to adjust the filter headline via an option, so that e.g. renaming to just `Tags` or `Labels` would be possible:

![grafik](https://user-images.githubusercontent.com/2056876/157036428-b20b9625-cb58-4f06-a12b-645010787d5b.png)

**Comment by olivM** [comment]
fixed in latest v0.0.6 release
