### ISSUE TITLE
Add option to set the tag type

### ISSUE THREAD

**Issue by 4n70w4** [Mahi-Mahi/SpatieTagsNovaFilter#4]
Hi! It would be nice to be able to set the tag type. Second argument of `withAllTags`.

![image](https://user-images.githubusercontent.com/38257723/168694632-ab14399f-a24c-45a5-b66f-f2451916f030.png)

**Comment by 4n70w4** [comment]
This type is also filtered during autocomplete.

![image](https://user-images.githubusercontent.com/38257723/168778556-1bc7e47b-ed6f-4c38-92b9-d600747ea5bd.png)

**Comment by olivM** [comment]
you can now pass the tag_type to withMeta : 
```
(new SpatieTagsNovaFilter())->withMeta([
    'tag_type' => 'content-category'
])
```

https://github.com/Mahi-Mahi/SpatieTagsNovaFilter/releases/tag/0.0.7
