### ISSUE TITLE
Add option to set matching type

### ISSUE THREAD

**Issue by 4n70w4** [Mahi-Mahi/SpatieTagsNovaFilter#5]
Hi! Out of the box, there is not only `withAllTags`, but also `WITHANYTAGS`, `WITHANYTAGSOFANYTYPE` and `WITHALLTAGSOFANYTYPE`.

It would be nice to be able to change the type of matching.

https://spatie.be/docs/laravel-tags/v4/basic-usage/retrieving-tagged-models

**Comment by olivM** [comment]
duplicate https://github.com/Mahi-Mahi/SpatieTagsNovaFilter/issues/4

**Comment by olivM** [comment]
duplicate https://github.com/Mahi-Mahi/SpatieTagsNovaFilter/issues/4
