### ISSUE TITLE
Show tag type in autocomplete

### ISSUE THREAD

**Issue by 4n70w4** [Mahi-Mahi/SpatieTagsNovaFilter#6]
Hi!

For example I have 3 tags with one name but with different type.

![image](https://user-images.githubusercontent.com/38257723/168775014-9a1c9918-423d-428e-a832-d7b59b11f0d3.png)

Currently all 3 tags seems look the same. It is not clear how to identify them.

![image](https://user-images.githubusercontent.com/38257723/168774779-bc243d59-c89a-465a-a050-d4b13e8b27b9.png)

**Comment by olivM** [comment]
fix in 0.0.8
